use anchor_lang::prelude::*;

pub mod errors;
pub mod events;
pub mod state;

mod approve_tx;
mod register_agent;
mod reject_tx;
mod set_enabled;
mod set_policy;
mod submit_auto;
mod submit_for_review;

// Glob re-export pulls in each instruction's Accounts struct *and* the
// `__client_accounts_*` modules generated by `#[derive(Accounts)]`. The
// `#[program]` macro below resolves them as `crate::__client_accounts_*`.
// The handler functions also collide across modules — that ambiguity is
// harmless because we always call them via the full `crate::<mod>::handler`
// path, never bare `handler`.
#[allow(ambiguous_glob_reexports)]
mod re_exports {
    pub use crate::approve_tx::*;
    pub use crate::register_agent::*;
    pub use crate::reject_tx::*;
    pub use crate::set_enabled::*;
    pub use crate::set_policy::*;
    pub use crate::submit_auto::*;
    pub use crate::submit_for_review::*;
}
pub use re_exports::*;

declare_id!("5Zy73PLH2hpNvsCvyeqpn2tKjHBXNihjX7UbeAZ41tQc");

#[program]
pub mod cardon {
    use super::*;

    pub fn register_agent(
        ctx: Context<RegisterAgent>,
        max_lamports_per_tx: u64,
        hitl_threshold_lamports: u64,
        daily_volume_ceiling: u64,
        allowed_programs: Vec<Pubkey>,
    ) -> Result<()> {
        crate::register_agent::handler(
            ctx,
            max_lamports_per_tx,
            hitl_threshold_lamports,
            daily_volume_ceiling,
            allowed_programs,
        )
    }

    pub fn set_policy(
        ctx: Context<SetPolicy>,
        max_lamports_per_tx: u64,
        hitl_threshold_lamports: u64,
        daily_volume_ceiling: u64,
        allowed_programs: Vec<Pubkey>,
    ) -> Result<()> {
        crate::set_policy::handler(
            ctx,
            max_lamports_per_tx,
            hitl_threshold_lamports,
            daily_volume_ceiling,
            allowed_programs,
        )
    }

    pub fn submit_auto(
        ctx: Context<SubmitAuto>,
        tx_hash: [u8; 32],
        lamports: u64,
        target_program: Pubkey,
    ) -> Result<()> {
        crate::submit_auto::handler(ctx, tx_hash, lamports, target_program)
    }

    pub fn submit_for_review(
        ctx: Context<SubmitForReview>,
        tx_hash: [u8; 32],
        lamports: u64,
        target_program: Pubkey,
    ) -> Result<()> {
        crate::submit_for_review::handler(ctx, tx_hash, lamports, target_program)
    }

    pub fn approve_tx(ctx: Context<ApproveTx>) -> Result<()> {
        crate::approve_tx::handler(ctx)
    }

    pub fn reject_tx(ctx: Context<RejectTx>, reason_code: u8) -> Result<()> {
        crate::reject_tx::handler(ctx, reason_code)
    }

    pub fn set_enabled(ctx: Context<SetEnabled>, enabled: bool) -> Result<()> {
        crate::set_enabled::handler(ctx, enabled)
    }
}
